services:
  api:
    build: .
    container_name: bankapi-api
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=bankapi-db
      - DB_PORT=5432
      - DB_NAME=bankapi
      - DB_USER=bankapi
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - bankapi-network

  db:
    image: postgres:16-alpine
    container_name: bankapi-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bankapi
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: bankapi
    volumes:
      - bankapi_data:/var/lib/postgresql/data
    networks:
      - bankapi-network

volumes:
  bankapi_data:

networks:
  bankapi-network:
    driver: bridge