services:
  api:
    build: .
    container_name: bankapi-api
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=bankapi-db
      - DB_PORT=5432
      - DB_NAME=bankapi
      - DB_USER=bankapi
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    external: true